title: Daniel Morim # your name (or website title) here
logo: "/images/Daniel - Profile 2024.1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 5+ years of experience in analytics, prediction and classification. Holds a master's degree in Data Science and a bachelor's degree in Electrical Engineering from Rio de Janeiro State University (Brazil). Previously at IoT and Smart Cities startups.
  <br><br>
  Working remotely from São Luís, Brazil, since 2022. 
  <br><br>
  <a href="https://www.linkedin.com/in/morim/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-M7S6F6TZCF # your Google Analytics tracking ID here
